wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: huggingface
    huggingface_version: 4.16.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1650652901
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      4: 3.8.8
      5: 0.12.15
      6: 4.16.2
      8:
      - 5
batch_size:
  desc: null
  value: 1
chunk_size:
  desc: null
  value: 512
dataset:
  desc: null
  value: dsl
epochs:
  desc: null
  value: 100
eval_freq:
  desc: null
  value: 500
eval_sim_threshold:
  desc: null
  value: 0.9
gen_beams:
  desc: null
  value: 5
gen_context:
  desc: null
  value: (define
gen_freq:
  desc: null
  value: 500
gen_len:
  desc: null
  value: 1024
gen_temp:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0001
max_grad_norm:
  desc: null
  value: 1
model:
  desc: null
  value: CodeBERTa
no_log:
  desc: null
  value: false
num_eval_samples:
  desc: null
  value: 100
room_mode:
  desc: null
  value: naive
seed:
  desc: null
  value: 42
warmup_proportion:
  desc: null
  value: 0.0002
weight_decay:
  desc: null
  value: 0.01
